baseURL = 'https://example.org/'
languageCode = 'fr-FR'
title = 'Agile Bordeaux'
theme = 'ananke'

[params]
  # Ananke affichera l'image si ce paramètre est présent dans le MD
  featured_image = "/media/agile-bordeaux.png"

[[menu.main]]
  name = 'Archives événements Meetup'
  url = '/events/'
  weight = 10
